services:
  accounts:
    image: "cihan0203/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mazebank
  loans:
    image: "cihan0203/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - mazebank
  cards:
    image: "cihan0203/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mazebank
networks:
  mazebank:
    driver: "bridge"