build:
  version: "2.0"

accounts:
  message: "Welcome to Maze Bank Accounts related QA APIs"
  contactDetails:
    name: "Mehmet Ali Kilinc - Qa Lead"
    email: "mehmetali@gmail.com"
  onCallSupport:
    - (555)342-1964
    - (544)430-1146