build:
  version: "1.0"

cards:
  message: "Welcome to Maze Bank Cards related prod APIs"
  contactDetails:
    name: "Kaan Cankaya - Product Owner"
    email: "kaan.cankaya@gmail.com"
  onCallSupport:
    - (545)672-2457
    - (547)651-8942