build:
  version: "3.0"

loans:
  message: "Welcome to Maze Bank Loans related local APIs"
  contactDetails:
    name: "Cihan Celik - Developer"
    email: "cihan.celik7@gmail.com"
  onCallSupport:
    - (533)582-1616
    - (532)270-1616
