spring:
  application:
    name: "configserver"
  profiles:
    active: git
    #active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/cihancelik7/mazebank-config.git"
          default-label: main
          clone-on-start: true
          force-pull: true
          timeout: 5
      # search-locations: "file:///Users//cihancelik//config"
encrypt:
 key: "45D81EC1EF61DF9AD8D3E5BB397F9"


server:
  port: 8071



