spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
         #search-loactions: "classpath:/config"
         search-locations: "file:///Users//cihancelik//config"


server:
  port: 8071